package:
  name: stopeight
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script_env:
    - CC
    - CXX

source:
  git_url: https://github.com/specpose/stopeight.git

requirements:
  build:
    - python
    - setuptools
#    - pybind11 # conda-forge
    - cmake # cmake
    - stopeight-clibs
    - pyqt >=5.6.0

  run:
    - python
    - vs2015_runtime  # [win]
    - stopeight-clibs
    - pyqt >=5.6.0
    - future
#    - six
    - funcsigs # [python2]
    - matplotlib
    - numpy

about:
  summary: Comparing sequences of points in 2 dimensions by visually overlapping them using matrix transformations (translation, scaling and rotation) and getting a boolean result.
  license_file: LICENSE.txt
