name: "Conda Build"

on: [push, pull_request]

jobs:
  conda-build-ubuntu:
    name: Ubuntu Conda Build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          activate-environment: btest
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule update --init --recursive
      - name: Bash
        shell: bash -l {0}
        run: |
          conda install --channel specpose stopeight-clibs
          python3 -m pip install setuptools
          python3 setup.py sdist bdist

  conda-build-mac:
    name: Mac Conda Build
    runs-on: 'macos-latest'
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          activate-environment: btest
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Checkout submodules
        shell: sh
        run: |
          git submodule update --init --recursive
      - name: Sh
        shell: sh -l {0}
        run: |
          conda install --channel specpose stopeight-clibs
          python3 -m pip install setuptools
          python3 setup.py sdist bdist

  conda-build-win:
    name: Windows Conda Build
    runs-on: 'windows-latest'
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          activate-environment: btest
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Checkout submodules
        shell: pwsh
        run: |
          git submodule update --init --recursive
      - name: PowerShell Core
        shell: pwsh
        run: |
          conda install --channel specpose stopeight-clibs
          python3 -m pip install setuptools
          python3 setup.py sdist bdist
