name: "Conda Build"

on: [push, pull_request]

jobs:
  conda-build-ubuntu:
    name: Ubuntu Conda Build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule update --init --recursive
      - name: Bash
        shell: bash
        run: |
          conda install conda-build
          conda build ./stopeight-clibs
          conda install --use-local stopeight-clibs
          /usr/share/miniconda/bin/python -m pip install setuptools wheel
          /usr/share/miniconda/bin/python setup.py bdist

  conda-build-mac:
    name: Mac Conda Build
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Checkout submodules
        shell: zsh
        run: |
          git submodule update --init --recursive
      - name: Zsh
        shell: zsh
        run: |
          source $CONDA/bin/activate
          conda create --name btest
          conda install -n btest conda-build
          conda activate -n btest
          conda init zsh
          cat .zshrc
          conda build -n btest --debug ./stopeight-clibs
          conda install -n btest --use-local stopeight-clibs
          conda run -n btest "python -m pip install setuptools wheel"
          conda run -n btest "python setup.py bdist"

  conda-build-win:
    name: Windows Conda Build
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Checkout submodules
        shell: pwsh
        run: |
          git submodule update --init --recursive
      - name: PowerShell Core
        shell: pwsh
        run: |
          $env:Path += ";"+$env:CONDA+";"+$env:CONDA+"\Scripts\"
          conda install conda-build
          Remove-Item -Path "C:\Program Files (x86)\Windows Kits\10\\include\wdf" -Recurse
          conda build ./stopeight-clibs
          conda install --use-local stopeight-clibs
          C:\Miniconda\python -m pip install setuptools wheel
          C:\Miniconda\python setup.py bdist
