name: "Conda Build"

on: [push, pull_request]

jobs:
  conda-build-ubuntu:
    name: Ubuntu Conda Build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Bash
        shell: bash -l {0}
        run: |
          git submodule update --init --recursive
          conda init bash
          conda create --name btest
          conda activate btest
          conda install conda-build
          conda build ./stopeight-clibs
          conda install --use-local stopeight-clibs
          pip install setuptools wheel
          python3 setup.py bdist

  conda-build-mac:
    name: Mac Conda Build
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Sh
        shell: sh -l {0}
        run: |
          git submodule update --init --recursive
          source $CONDA/bin/activate
          conda init zsh
          conda create --name btest
          conda activate btest
          conda install conda-build
          conda build --debug ./stopeight-clibs
          conda install --use-local stopeight-clibs
          pip install setuptools wheel
          python3 setup.py bdist

  conda-build-win:
    name: Windows Conda Build
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: PowerShell Core
        shell: pwsh
        run: |
          git submodule update --init --recursive
          SET PATH=%PATH%;%CONDA%;%CONDA%\Scripts\
          conda init powershell
          conda create --name btest
          conda activate btest
          conda install conda-build
          rd /s /q "C:\Program Files (x86)\Windows Kits\10\\include\wdf"
          conda build ./stopeight-clibs
          conda install --use-local stopeight-clibs
          pip install setuptools wheel
          python3 setup.py bdist
