name: "Conda Build"

on: [push, pull_request]

jobs:
  conda-build-ubuntu:
    name: Ubuntu Conda Build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Checkout submodules
        shell: bash -l {0}
        run: |
          git submodule update --init --recursive
      - name: Bash
        shell: bash -l {0}
        run: |
          $CONDA/bin/conda create --name btest
          $CONDA/bin/conda activate btest
          which conda
          conda install --channel specpose stopeight-clibs
          which python
          python -m pip install setuptools wheel
          python setup.py sdist bdist

  conda-build-mac:
    name: Mac Conda Build
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Checkout submodules
        shell: sh -l {0}
        run: |
          git submodule update --init --recursive
      - name: Sh
        shell: sh -l {0}
        run: |
          $CONDA/bin/conda create --name btest
          $CONDA/bin/conda activate btest
          which conda
          conda install --channel specpose stopeight-clibs
          which python
          python -m pip install setuptools wheel
          python setup.py sdist bdist

  conda-build-win:
    name: Windows Conda Build
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Checkout submodules
        shell: cmd /C CALL {0}
        run: |
          git submodule update --init --recursive
      - name: Cmd.exe
        shell: cmd /C CALL {0}
        run: |
          "%CONDA%"\condabin\conda create --name btest
          "%CONDA%"\condabin\conda activate btest
          conda install --channel specpose stopeight-clibs
          python -m pip install setuptools wheel
          python setup.py sdist bdist
